apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-target-service
  namespace: secure-devops-demo
  labels:
    app: demo-target-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-target-service
  template:
    metadata:
      labels:
        app: demo-target-service
    spec:
      containers:
        - name: demo-target-service
          image: demo-target-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
      securityContext:
        fsGroup: 1000
