apiVersion: v1
kind: Service
metadata:
  name: demo-target-service
  namespace: secure-devops-demo
spec:
  selector:
    app: demo-target-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
